version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 10
    reviewers:
      - "XenoAmess"
    assignees:
      - "XenoAmess"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    labels:
      - "dependencies"
      - "java"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "com.puppycrawl.tools:checkstyle"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 5
    reviewers:
      - "XenoAmess"
    assignees:
      - "XenoAmess"
    commit-message:
      prefix: "build(deps)"
    labels:
      - "dependencies"
      - "github_actions"
